name = "GLM 4.6 TEE"
release_date = "2024-01-01"
last_updated = "2024-01-01"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.75
output = 2.00

[limit]
context = 203_000
input = 203_000
output = 65_535

[modalities]
input = ["text"]
output = ["text"]
