name = "Compound Mini"
family = "groq"
release_date = "unknown"
last_updated = "unknown"
attachment = false
reasoning = false
temperature = true
knowledge = "unknown"
tool_call = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
