name = "OpenAI o4-mini high"
release_date = "2024-01-01"
last_updated = "2024-01-01"
attachment = false
reasoning = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.1
output = 4.4

[limit]
context = 200_000
input = 200_000
output = 100_000

[modalities]
input = ["text"]
output = ["text"]
