name = "Minimax/Minimax-M2"
attachment = false
reasoning = true
tool_call = true
temperature = true
structured_output = false
open_weights = false

[limit]
context = 200_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
