name = "Qwen 3 235b A22B"
release_date = "2025-07-21"
last_updated = "2025-07-21"
attachment = true
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.3
output = 0.5

[limit]
context = 41_000
input = 41_000
output = 32_768

[modalities]
input = ["text", "pdf"]
output = ["text"]
