name = "MiniMax M2-her"
release_date = "2026-01-24"
last_updated = "2026-01-24"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.302
output = 1.207

[limit]
context = 65_532
input = 65_532
output = 2_048

[modalities]
input = ["text"]
output = ["text"]
