name = "GLM 4.5"
attachment = false
reasoning = true
tool_call = true
temperature = true
structured_output = false
open_weights = false

[limit]
context = 131_072
output = 98_304

[modalities]
input = ["text"]
output = ["text"]
