name = "Qwen3 30B A3B"
attachment = false
reasoning = true
tool_call = true
temperature = true
structured_output = false
open_weights = false

[limit]
context = 40_000

[modalities]
input = ["text"]
output = ["text"]
