name = "Qwen3-Max-N"
release_date = "2025-11-05"
last_updated = "2025-11-05"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = false

[limit]
context = 256_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
